name: Build and Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip
      # Checkout the repository
    
      - name: Checkout Git repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js 18.10.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.10.0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true 

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.2

      # Install dependencies and build Angular app
      - name: Install dependencies and build Angular app
        run: |
          cd Agora-Voyage/frontend
          npm ci
          npm run build

      # Install Go dependencies
      - name: Install Go dependencies
        run: go mod download

      # Lint Golang
      - name: Lint Golang
        run: go fmt ./...

      # Lint Angular
      - name: Lint Angular
        run: |
          cd Agora-Voyage/frontend
          npm run lint

      # Test Golang
      - name: Test Golang
        run: go test ./...

      # Test Angular (if applicable)
      - name: Test Angular
        run: |
          # Add Angular test script here if available

      # Build artifacts for deployment (if applicable)
      - name: Build artifacts
        run: |
          # Add build script for artifacts generation if applicable

      # Create release or deploy to production (if applicable)
      - name: Deploy
        run: |
          # Add deployment script here if applicable
